apiVersion: v1
data:
  timer.yaml: |-
    name: "timer"
    ip: ${POD_IP}
    etcd:
      - vanus-etcd-0.vanus-etcd:2379
      - vanus-etcd-1.vanus-etcd:2379
      - vanus-etcd-2.vanus-etcd:2379
    metadata:
      key_prefix: ""
    leader_election:
      lease_duration: 15
    timingwheel:
      tick: 1
      wheel_size: 32
      layers: 4
    controllers:
      - vanus-controller-0.vanus-controller.vanus.svc:2048
      - vanus-controller-1.vanus-controller.vanus.svc:2048
    observability:
      metrics:
        enable: true
      tracing:
        enable: false
kind: ConfigMap
metadata:
  name: config-timer
  namespace: vanus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-timer
  name: vanus-timer
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-timer
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: vanus-timer
    spec:
      #nodeSelector:
      #  type: calculation
      containers:
        - name: timer
          image: ifplusor/vanus-timer:v0.7.0-benchmark1
          imagePullPolicy: IfNotPresent
          env:
            - name: VANUS_LOG_LEVEL
              value: DEBUG
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 2112
              protocol: TCP
              name: metrics
          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 2000m
              memory: 4000Mi
          volumeMounts:
            - name: config-timer
              mountPath: /vanus/config
        - name: node-exporter
          image: prom/node-exporter
          args:
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          ports:
            - containerPort: 9100
              protocol: TCP
              name: metrics
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
      volumes:
        - name: config-timer
          configMap:
            name: config-timer
