apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: benchmark-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    resources:
      requests:
        memory: 23Gi
        cpu: "8"
      limits:
        memory: 23Gi
        cpu: "8"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      auto.create.topic.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: persistent-claim
      size: 600Gi
      class: local
      deleteClaim: true
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 3Gi
        cpu: "2"
      limits:
        memory: 3Gi
        cpu: "2"
    storage:
      type: persistent-claim
      size: 10Gi
      class: local
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
